### ISSUE TITLE
Way to get just the suffix

### ISSUE THREAD

**Issue by gleich** [gleich/ordinal#2]
Hello!  What do you think of exposing a function that returns a `String` with the suffix (e.g. `th`). I would love to make a PR for this!

**Comment by dtolnay** [comment]
If you are interested in this crate, can I just transfer the repo and crates.io package over to you and you can maintain it? This is learning-rust code from \>5 years ago that I don't care about.

**Comment by gleich** [comment]
Sure. Let me know if there is anything I need to do on my end for the transfers.

**Comment by dtolnay** [comment]
Done. You'll need to click accept somewhere on GitHub (check email or top of https://github.com/dtolnay/ordinal) and somewhere on crates.io (https://crates.io/me/pending-invites).

**Comment by gleich** [comment]
Accepted everything
